"""Add jsx_code to block_templates

Revision ID: 524cbc1dc7fb
Revises: e4121998e534
Create Date: 2025-05-26 16:44:12.811104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524cbc1dc7fb'
down_revision: Union[str, None] = 'e4121998e534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_templates', sa.Column('jsx_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block_templates', 'jsx_code')
    # ### end Alembic commands ###
