"""Add category and description to settings

Revision ID: 8d93e8a8b20c
Revises: 4a44a4f6a9cc
Create Date: 2025-05-23 15:49:30.442959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d93e8a8b20c'
down_revision: Union[str, None] = '4a44a4f6a9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('category', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'description')
    op.drop_column('settings', 'category')
    # ### end Alembic commands ###
