"""Add batch processing table

Revision ID: add_batch_processing_table
Revises: 4a44a4f6a9cc
Create Date: 2025-01-06 16:27:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'add_batch_processing_table'
down_revision = '4a44a4f6a9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(255), nullable=False),
    sa.Column('status', sa.String(50), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False, default=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False, default=0),
    sa.Column('failed_count', sa.Integer(), nullable=False, default=0),
    sa.Column('current_file_index', sa.Integer(), nullable=False, default=0),
    sa.Column('current_file', sa.Text(), nullable=True),  # JSON string
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=False),  # JSON string
    sa.Column('files', sa.Text(), nullable=False),  # JSON string
    sa.Column('processing_stats', sa.Text(), nullable=True),  # JSON string
    sa.Column('results', sa.Text(), nullable=True),  # JSON string
    sa.Column('errors', sa.Text(), nullable=True),  # JSON string
    sa.Column('logs', sa.Text(), nullable=True),  # JSON string
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_processing_jobs_batch_id'), 'batch_processing_jobs', ['batch_id'], unique=True)
    op.create_index(op.f('ix_batch_processing_jobs_status'), 'batch_processing_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_processing_jobs_status'), table_name='batch_processing_jobs')
    op.drop_index(op.f('ix_batch_processing_jobs_batch_id'), table_name='batch_processing_jobs')
    op.drop_table('batch_processing_jobs')
    # ### end Alembic commands ###