"""Add icon field to BlockCategory

Revision ID: e4121998e534
Revises: bec7a394752c
Create Date: 2025-05-26 14:43:07.554928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4121998e534'
down_revision: Union[str, None] = 'bec7a394752c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_categories', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block_categories', 'icon')
    # ### end Alembic commands ###
