"""Refactor OcrResult: add directory_id, pdf_text, pdf_image_path, ocr_image_path, timestamps

Revision ID: f77949387bc2
Revises: 55b67baf3177
Create Date: 2025-05-23 12:27:44.374413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77949387bc2'
down_revision: Union[str, None] = '55b67baf3177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_results', sa.Column('directory_id', sa.String(), nullable=True))
    op.add_column('ocr_results', sa.Column('pdf_text', sa.Text(), nullable=True))
    op.add_column('ocr_results', sa.Column('pdf_image_path', sa.Text(), nullable=True))
    op.add_column('ocr_results', sa.Column('ocr_image_path', sa.Text(), nullable=True))
    op.add_column('ocr_results', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('ocr_results', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocr_results', 'updated_at')
    op.drop_column('ocr_results', 'created_at')
    op.drop_column('ocr_results', 'ocr_image_path')
    op.drop_column('ocr_results', 'pdf_image_path')
    op.drop_column('ocr_results', 'pdf_text')
    op.drop_column('ocr_results', 'directory_id')
    # ### end Alembic commands ###
